### Abstract

```{r get_abstract_intro_vals, echo = FALSE, message=FALSE, warning=FALSE}
# identify how many regions were in the survey for the text (as 'several', 'one', many...)
spawning_grounds_statement <- ifelse(isTRUE(current_shumagins_survey),
  "several of their main spawning grounds.",
  ifelse(length(unique(event_data_shelikof$region)) == 1,
    "their primary spawning grounds.",
    paste0(english::as.english(length(unique(event_data_shelikof$region))), " of their primary spawning grounds.")
  )
)

# identify the start-end dates for each survey, and create a sentence summarizing this

# for shumagins
if (isTRUE(current_shumagins_survey)) {
  region_names_shumagins <- unique(current_year_event_data$region[current_year_event_data$SURVEY == survey_shumagins])

  if (length(region_names_shumagins) > 1) {
    modifier <- "were"
  } else {
    modifier <- "was"
  }

  shumagins_sentence1 <- knitr::combine_words(region_names_shumagins)
  shumagins_sentence2 <- paste0(shumagins_sentence1, " ", modifier)


  # also pulling out start/end dates (this can be modified based on what people prefer in the text, but currently using first interval_start_date and last interval_end_date)
  shum_start_date <- format(as.Date(min(current_year_interval_data$START_TIME[current_year_interval_data$SURVEY == survey_shumagins], na.rm = TRUE)), format = "%B %d")
  shum_end_date <- format(as.Date(max(current_year_interval_data$END_TIME[current_year_interval_data$SURVEY == survey_shumagins], na.rm = TRUE)), format = "%B %d")

  shumagins3 <- paste0(shumagins_sentence1, " (", as.character(survey_shumagins), "; ", shum_start_date, "-", shum_end_date, ") and")
}

# for the Shelikof survey, was ALWAYS ASSUME there was one... we'll have to modify if that isn't the case!

# identify the survey regions
region_names_shelikof <- unique(current_year_event_data$region[current_year_event_data$SURVEY == survey_shelikof])

if (length(region_names_shelikof) > 1) {
  modifier <- "were"
} else {
  modifier <- "was"
}

shelikof_sentence1 <- knitr::combine_words(region_names_shelikof)
shelikof_sentence2 <- paste0(shelikof_sentence1, " ", modifier)

# also pulling out start/end dates (this is rough, and can be modified based on what people prefer in the text, but currently using irst interval_start_date and last interval_end_date)

shel_start_date <- format(as.Date(min(current_year_interval_data$START_TIME[current_year_interval_data$SURVEY == survey_shelikof], na.rm = TRUE)), format = "%B %d")
shel_end_date <- format(as.Date(max(current_year_interval_data$START_TIME[current_year_interval_data$SURVEY == survey_shelikof], na.rm = TRUE)), format = "%B %d")

# identify the survey years (and missed survey years) for the Shumgins
if (isTRUE(current_shumagins_survey)) {
  # identified the survey years (and missed survey years) in each Shumagins survey; this starts in 2009 for Shumagins
  shumagins_post_2009_survey_years <- read_csv(survey_params_shumagins_selectivity_corrected_surveys) %>%
    mutate(year = as.numeric(substr(surveys, 1, 4))) %>%
    select(year)

  # all possible years
  shumagins_possible_years <- seq(min(shumagins_post_2009_survey_years$year), current_year - 1, 1)

  # use this to identify the missing years
  shumagins_missing_years <- shumagins_possible_years[!(shumagins_possible_years %in% shumagins_post_2009_survey_years$year)]

  # and add in the pre-2009 missing years
  shumagins_missing_years <- c(2004, shumagins_missing_years)

  # and add a statement of what years we've done a shumagins survey
  shumagins_survey_sentence <- paste0("The Shumagin Islands area has been surveyed annually in winter since 2001 (except in ", combine_words(shumagins_missing_years), "), as well as in 1994, 1995, and 1996.")
}

# identified the survey years (and missed survey years) in each Shelikof survey; this starts in 2008 for Shelikof
shelikof_post_2008_survey_years <- read_csv(survey_params_shelikof_selectivity_corrected_surveys) %>%
  mutate(year = as.numeric(substr(surveys, 1, 4))) %>%
  select(year)

# all possible years
shelikof_possible_years <- seq(min(shelikof_post_2008_survey_years$year), current_year, 1)

# use this to identify the missing years
shelikof_missing_years <- shelikof_possible_years[!(shelikof_possible_years %in% shelikof_post_2008_survey_years$year)]

# and add in the pre-2009 missing years
shelikof_missing_years <- c(1982, 1989, shelikof_missing_years)


# get the primary analysis (selectivity, nearest haul) estimates;
# sum up all the values by region, present as millions of fish/ metric tons

# for the shumagins (if we've got a survey there)
if (isTRUE(current_shumagins_survey)) {
  shumagins_summary_vals <- current_year_pollock_biomass_nums %>%
    filter(SURVEY == survey_shumagins) %>%
    group_by(region) %>%
    summarize(
      num_million = sum(NUMBERS) / 1e6,
      biomass_mt = sum(BIOMASS) / 1e3
    )

  # build a summary sentence
  shumagins_bio_num_sentence <- paste0("The amount of walleye pollock for the winter ", current_year, " Shumagin Islands survey was estimated to be ", print_n_decimal(sum(shumagins_summary_vals$num_million), 0), " million fish weighing ", print_n_decimal(sum(shumagins_summary_vals$biomass_mt), 0), " metric tons (t) (including the ", combine_words(shumagins_summary_vals$region), " regions).")
}

# for the Shelikof
shelikof_summary_vals <- current_year_pollock_biomass_nums %>%
  filter(SURVEY == survey_shelikof) %>%
  group_by(region) %>%
  summarize(
    num_million = sum(NUMBERS) / 1e6,
    biomass_mt = sum(BIOMASS) / 1e3
  )


# Build the appropriate sentence for the abstract based on the regions surveyed in this year. Add a sentence for each region!
shelikof_summary_sentences <- c()
shelikof_region_summaries <- c()
for (i in unique(current_year_interval_data$region[current_year_interval_data$SURVEY == survey_shelikof])) {
  shelikof_summary_sentences <- rbind(
    shelikof_summary_sentences,
    paste0("The amount of walleye pollock for the ", current_year, " ", i, " survey was ", print_n_decimal(shelikof_summary_vals$num_million[shelikof_summary_vals$region == i], 0), " million fish weighing ", print_n_decimal(shelikof_summary_vals$biomass_mt[shelikof_summary_vals$region == i], 0), " t.")
  )

  shelikof_region_summaries <- rbind(shelikof_region_summaries, i)
}

# now identify which belongs to shelikof strait
shelikof_summary_sentence <- shelikof_summary_sentences[which(shelikof_region_summaries == "Shelikof Strait")]

# and which (if any) belong to Marmot/Chirikof
marmot_chirikof_sentences <- shelikof_summary_sentences[which(shelikof_region_summaries != "Shelikof Strait")]


# get the non-selectivity estimates; present as millions of fish, and biomass metric tons
# limit these to just the MAIN part of the Sheliof and Shumagins survey

# Drop the non-selectivity estimate from the abstract? Its been long enough.
# 
# if (isTRUE(current_shumagins_survey)) {
#   shum_non_sel_num_million <- sum(shumagins_analysis_comparisons$NUMBERS[shumagins_analysis_comparisons$DATA_SET_ID == shumagins_non_sel_data_set & shumagins_analysis_comparisons$ANALYSIS_ID == shumagins_non_sel_analysis & shumagins_analysis_comparisons$region == "Shumagin Islands"]) / 1e6
# 
#   shum_non_sel_biomass_mt <- sum(shumagins_analysis_comparisons$BIOMASS[shumagins_analysis_comparisons$DATA_SET_ID == shumagins_non_sel_data_set & shumagins_analysis_comparisons$ANALYSIS_ID == shumagins_non_sel_analysis & shumagins_analysis_comparisons$region == "Shumagin Islands"]) / 1e3
# 
#   shum_num_million <- shumagins_summary_vals$num_million[shumagins_summary_vals$region == "Shumagin Islands"]
#   shum_biomass_mt <- shumagins_summary_vals$biomass_mt[shumagins_summary_vals$region == "Shumagin Islands"]
# 
#   # and calculate difference between estimates- primary vs non-selectivity
#   shum_nums_primary_vs_non_sel <- ((shum_non_sel_num_million - shum_num_million) / shum_num_million) * 100
#   shum_biomass_primary_vs_non_sel <- ((shum_non_sel_biomass_mt - shum_biomass_mt) / shum_biomass_mt) * 100
# 
#   shumagins_only_select_comp_sentence <- paste0("The no-selectivity analysis estimated slightly more biomass ", round(shum_biomass_primary_vs_non_sel, digits = 1), "% higher in the Shumagin Islands. ")
# }
# 
# shel_non_sel_num_million <- sum(shelikof_analysis_comparisons$NUMBERS[shelikof_analysis_comparisons$DATA_SET_ID == shelikof_non_sel_data_set & shelikof_analysis_comparisons$ANALYSIS_ID == shelikof_non_sel_analysis & shelikof_analysis_comparisons$region == "Shelikof Strait"]) / 1e6

# shel_num_million <- shelikof_summary_vals$num_million[shelikof_summary_vals$region == "Shelikof Strait"]
# shel_biomass_mt <- shelikof_summary_vals$biomass_mt[shelikof_summary_vals$region == "Shelikof Strait"]
# 
# shel_non_sel_biomass_mt <- sum(shelikof_analysis_comparisons$BIOMASS[shelikof_analysis_comparisons$DATA_SET_ID == shelikof_non_sel_data_set & shelikof_analysis_comparisons$ANALYSIS_ID == shelikof_non_sel_analysis & shelikof_analysis_comparisons$region == "Shelikof Strait"]) / 1e3

# and calculate difference between estimates- primary vs non-selectivity
# shel_nums_primary_vs_non_sel <- ((shel_non_sel_num_million - shel_num_million) / shel_num_million) * 100
# shel_biomass_primary_vs_non_sel <- ((shel_non_sel_biomass_mt - shel_biomass_mt) / shel_biomass_mt) * 100

# related text (left out):

# These estimates were based on an analysis where length-frequency distributions of all species were assigned to observed backscatter using biological data and species compositions of the hauls nearest that backscatter. It also included a correction for escapement of fishes and other catch from the survey trawl (i.e. net selectivity). `r ifelse(shel_biomass_primary_vs_non_sel > 1, paste0('This result was compared with an analysis not incorporating net selectivity.',shumagins_only_select_comp_sentence,'The Shelikof Strait no-selectivity analysis estimated slightly ',ifelse(shel_biomass_primary_vs_non_sel >0, 'more', 'less'),' biomass (',round(shel_biomass_primary_vs_non_sel, digits = 1),'%) as compared to the primary analysis.'),' ')`

# build a few blank statements for cases where we don't have data (no Shumgins survey/no ages yet)
if (!isTRUE(current_shumagins_survey)) {
  shumagins3 <- ""
  shumagins_survey_sentence <- ""
  shumagins_bio_num_sentence <- ""
  shumagins_only_select_comp_sentence <- ""
}
```

Scientists from the Alaska Fisheries Science Center conducted acoustic-trawl surveys in the Gulf of Alaska during late winter `r current_year` to estimate the distribution and abundance of walleye pollock (*Gadus chalcogrammus*) at `r spawning_grounds_statement` These pre-spawning walleye pollock surveys covered the `r shumagins3` `r shelikof_sentence1` (`r as.character(survey_shelikof)`; `r paste0(shel_start_date, "-", shel_end_date )`) `r ifelse(length(unique(current_year_pollock_biomass_nums$region[current_year_pollock_biomass_nums$SURVEY == survey_shelikof])) == 1, 'area', 'areas')`. `r shumagins_survey_sentence` The Shelikof Strait area has been surveyed annually in winter since 1981 (except in `r combine_words(shelikof_missing_years)`).

`r shumagins_bio_num_sentence` `r shelikof_summary_sentence` Walleye pollock between 45 and 64 cm fork length (FL) were primarily composed of the 10-year-old 2012 year class (27% of total biomass). Pollock between 35 and 44 cm FL consisted primarily of 4- and 5-year-old fish from the 2018 and 2017 year classes (20 and 19% of the biomass, respectively). The 17 to 25 cm FL age-2 fish from the 2020 year class were numerically the most abundant (29% of total abundance) but contributed less than 3% to the total biomass. Very few age-1 pollock (<16 cm FL) from the 2021 year class were observed (<2% of total abundance). `r marmot_chirikof_sentences`


