<!-- TABLES-->
<!-- NOTE- tables 1,2 (calibration parameters, selectivity curves) are not produced here!-->

<!-- TABLES-->

<!-- Insert calibration parameters table already made in a Word document-->
```{r add_cal_table, echo = FALSE, message=FALSE, warning=FALSE, fig.width=6.5}
## NOTE! This will need to be updated for 2024 still!

officer::block_caption(
  label = paste0("Simrad EK80 38 kHz acoustic system description and settings used during the ", current_year, " winter acoustic-trawl surveys. These include environmental parameters and results from standard sphere acoustic system calibrations conducted in association with the survey and final values used to calculate biomass & abundance data. The collection settings column contains 12 February EK80 calibration utility results. Other columns are a combination of on-axis and EK80 calibration utility results (see Methods and Results and Discussion sections of text for details)."),
  style = "Table Caption",
  autonum = run_autonum(
    seq_id = "tab",
    bkm = "caltable",
    pre_label = "Table ",
    post_label = ". -- "
  )
)

officer::block_pour_docx("2024_cal_table.docx")

```

<!-- Set as portrait- this extends back to the last 'block_section' call-->
`r  block_section(portrait_section)`

<!-- haul tables -->
```{r haul_table, echo = FALSE, message=FALSE, warning=FALSE, results='asis', fig.width=9}
# return table and caption to the document

# remove 'non-scaling' hauls? NATE not sure if you want the incompete haul, if you do, get rid of this

# remove the hauls that weren't used in the analysis
haul_table_data <- haul_table_data[haul_table_data$EVENT_ID %in% scaling_hauls$EVENT_ID,]

tmp_table <- MACEReports::build_haul_table(haul_data = haul_table_data)

# print table and caption
print_table <- set_caption(tmp_table[[1]],
  caption = tmp_table[[2]],
  style = "Table caption",
  align_with_table = FALSE,
  autonum = run_autonum(
    seq_id = "tab",
    bkm = "surveyhaultable",
    pre_label = "Table ",
    post_label = ". -- "
  )
)

flextable_to_rmd(x = print_table, ft.align = "left", ft.split = FALSE, ft.keepnext = FALSE, print = TRUE)

```

<!-- Set as landscape- this extends back to the last 'block_section' call -->
`r  block_section(landscape_section)`

<!-- specimen tables -->
```{r specimen_table, echo = FALSE, message=FALSE, warning=FALSE, results='asis', fig.width=6.5}
# return the table and caption
tmp_table <- build_specimen_table_function(specimen_table_data = specimen_table_data)

# print table and caption
print_table <- set_caption(tmp_table[[1]],
  caption = tmp_table[[2]],
  style = "Table Caption",
  align_with_table = FALSE,
  autonum = run_autonum(
    seq_id = "tab",
    bkm = "surveyspecimen",
    pre_label = "Table ",
    post_label = ". -- "
  )
)

flextable_to_rmd(x = print_table, ft.align = "left", ft.split = FALSE, ft.keepnext = FALSE, print = TRUE)

```

\newpage

<!-- make catch tables for each gear type in the Shelikof Strait-->
```{r catch_table, echo = FALSE, message=FALSE, warning=FALSE, results='asis', fig.width=6.5}

# the function build_catch_table_by_region just takes the dataframe 'catch_table_data' and pretties it up- this data
# is already combined into one 'bogoslof' region so it works survey-wide (no umnak/samalga split) 
# (this happends in get_catch_table_data.R).

tmp_table <- build_catch_table_by_region(region_name = "Bogoslof")


# print table and caption
print_table <- set_caption(tmp_table[[1]][[1]],
  caption = tmp_table[[1]][[2]],
  style = "Table Caption",
  align_with_table = FALSE,
  autonum = run_autonum(
    seq_id = "tab",
    bkm = "bogosloflfs1421catch",
    pre_label = "Table ",
    post_label = ". -- "
  )
)

flextable_to_rmd(x = print_table, ft.align = "left", ft.split = FALSE, ft.keepnext = FALSE, print = TRUE)

```

<!-- Set as portrait- this extends back to the last 'block_section' call-->
`r  block_section(portrait_section)`

\newpage

<!-- Insert biomass time series by area table already made in a Word document-->
```{r add_biomass_series_table, echo = FALSE, message=FALSE, warning=FALSE, fig.width=9}

officer::block_caption(
  label = paste0("Walleye pollock biomass (tons (t)) estimated by survey area and management area from February-March acoustic-trawl surveys in the Bogoslof Island area between 1988 and 2024."),
  style = "Table Caption",
  autonum = run_autonum(
    seq_id = "tab",
    bkm = "biotable",
    pre_label = "Table ",
    post_label = ". -- "
  )
)

officer::block_pour_docx("Biomass_by_area_time_series_table.docx")

```

<!-- Set as portrait- this extends back to the last 'block_section' call-->
`r  block_section(portrait_section)`

\newpage

<!-- biomass and numbers at length and age tables-->


<!-- biomass and numbers at length-->
```{r nums_at_length_table, echo = FALSE, message=FALSE, warning=FALSE, results='asis', fig.width=9}
# return the table and caption
temp_dat = historical_surveys_pollock_totals_by_length
# Relabel all the regions as bogoslof so they will all be compiled into the tables by length
temp_dat$region = "Bogoslof"
# Remove all rows with 0, since these will show up as <1 and we don't want that.
temp_dat = subset(temp_dat,BIOMASS>0)
tmp_table <- MACEReports::build_numbers_at_length_table_winter_goa(biomass_nums_length_data = temp_dat, region = "Bogoslof")

# print table and caption
print_table <- set_caption(tmp_table[[1]],
  caption = tmp_table[[2]],
  style = "Table Caption",
  align_with_table = FALSE,
  autonum = run_autonum(
    seq_id = "tab",
    bkm = "numlength",
    pre_label = "Table ",
    post_label = ". -- "
  )
)

flextable_to_rmd(x = print_table, ft.align = "left", ft.split = FALSE, ft.keepnext = FALSE, print = TRUE)

cat("\\pagebreak")
```


`r  block_section(landscape_section)`

```{r biomass_at_length_table, echo = FALSE, message=FALSE, warning=FALSE, results='asis', fig.width=9}
# return the table and caption
tmp_table <- MACEReports::build_biomass_at_length_table_winter_goa(biomass_nums_length_data = temp_dat, region = "Bogoslof")

# print table and caption
print_table <- set_caption(tmp_table[[1]],
  caption = tmp_table[[2]],
  style = "Table Caption",
  align_with_table = FALSE,
  autonum = run_autonum(
    seq_id = "tab",
    bkm = "biolength",
    pre_label = "Table ",
    post_label = ". -- "
  )
)

flextable_to_rmd(x = print_table, ft.align = "left", ft.split = FALSE, ft.keepnext = FALSE, print = TRUE)

cat("\\pagebreak")
```

`r  block_section(landscape_section)`

<!-- Insert maturity percent by year and region already made in a Word document-->
```{r add_maturity_table, echo = FALSE, message=FALSE, warning=FALSE, fig.width=6.5}

officer::block_caption(
  label = paste0("Unweighted percent female walleye pollock in spawning and post-spawning maturity condition by regions during Bogoslof survey years 1988-2020. Percentages greater than 50% are outlined, and n = total number of female pollock examined."),
  style = "Table Caption",
  autonum = run_autonum(
    seq_id = "tab",
    bkm = "mattable",
    pre_label = "Table ",
    post_label = ". -- "
  )
)

officer::block_pour_docx("Maturity_table.docx")

```

<!-- Set as portrait- this extends back to the last 'block_section' call-->
`r  block_section(portrait_section)`